#!/bin/sh

. `dirname $0`/support.sh

mkdir -p ${fixtures_dir}

# generate a good database
rm -f ${fixtures_dir}/good
for i in `seq 1 5` ; do
	echo "pw$i" | $PW_INSERT -d ${fixtures_dir}/good -t- "entry$i"
done
for i in `seq 6 8` ; do
	echo "pw$i\nUser: hidden-entry$i\nPIN: $i$i" | $PW_INSERT -d ${fixtures_dir}/good -t-
done

# generate a broken database
cat ${fixtures_dir}/good | \
	sed -e 's/entry2:...../entry2:XXXXX/' | \
	sed -e '7d' | \
	sed -e '4 {s/^1/9/}' | \
	cat > ${fixtures_dir}/bad

# This is free software released into the public domain (CC0 license).
