#!/bin/sh

. `dirname $0`/support.sh

PW_SHOW_GOOD="$PW_SHOW -d ${fixtures_dir}/good"
PW_SHOW_BAD="$PW_SHOW -d ${fixtures_dir}/bad"

echo "pw-show ($PW_SHOW)..."
echo

echo "...accepts empty dbs"
$PW_SHOW -d /dev/null && ok || failed

echo "...does not accept directories"
$PW_SHOW -d /tmp && failed || ok

echo "...complains about missing dbs (absolute)"
$PW_SHOW -d /tmp/does-not-exist && failed || ok

echo "...complains about missing dbs (relative)"
$PW_SHOW -d does-not-exist && failed || ok

echo "...searches dbs in XDG_DATA_HOME"
mkdir -p /tmp/xdg/pw
cp ${fixtures_dir}/good /tmp/xdg/pw
XDG_DATA_HOME=/tmp/xdg $PW_SHOW -d good && ok || failed
rm /tmp/xdg/pw/good
rmdir /tmp/xdg/pw
rmdir /tmp/xdg

echo "...with no params shows all records"
num_records=$($PW_SHOW -d ${fixtures_dir}/good | wc -l)
[ "$num_records" -eq 8 ] && ok || failed

echo "...complains about broken records but goes on"
num_records=$($PW_SHOW -d ${fixtures_dir}/bad | wc -l)
[ "$num_records" -eq 5 ] && ok || failed

echo "...returns an error if it cannot find any matching entry"
$PW_SHOW_GOOD 'non-existing' && failed || ok

echo "...searches on all fields"
pw=$($PW_SHOW_GOOD 'hidden-entry6')
[ "$pw" = "pw6" ] && ok || failed

echo "...searches only certain fields (part 1, the correct ones)"
pw=$($PW_SHOW_GOOD -s 'PIN' '66')
[ "$pw" = "pw6" ] && ok || failed

echo "...searches only certain fields (part 2, not others)"
$PW_SHOW_GOOD -s 'PIN' 'hidden-entry6' && failed || ok

echo "...searches only in labels (part 1, only in labels)"
pw=$($PW_SHOW_GOOD -l 'entry5')
[ "$pw" = "pw5" ] && ok || failed

echo "...searches only in labels (part 2, not in other fields)"
$PW_SHOW_GOOD -l 'hidden-entry6' && failed || ok

echo "...requires a label/pattern when a field is specified"
$PW_SHOW_GOOD -l && failed || ok

echo "...shows only the requested field"
pin=$($PW_SHOW_GOOD -f 'PIN' 'hidden-entry6')
[ "$pin" = "66" ] && ok || failed

echo "...refuses to show only one field when using --complete"
$PW_SHOW_GOOD -f 'PIN' -c 'hidden-entry6' && failed || ok

echo "...refuses to decode an entry with an unknown version number"
$PW_SHOW_BAD -l 'entry4' && failed || ok
