#!/bin/sh

. `dirname $0`/support.sh

PW_SHOW_GOOD="$PW_SHOW -d ${fixtures_dir}/good"

echo "pw-show ($PW_SHOW)..."
echo

echo "...accepts empty dbs"
$PW_SHOW -d /dev/null && ok || failed

echo "...does not accept directories"
$PW_SHOW -d /tmp && failed || ok

echo "...complains about missing dbs"
$PW_SHOW -d /tmp/does-not-exist && failed || ok

echo "...with no params shows all records"
num_records=$($PW_SHOW -d ${fixtures_dir}/good | wc -l)
[ "$num_records" -eq 8 ] && ok || failed

echo "...complains about broken records but goes on"
num_records=$($PW_SHOW -d ${fixtures_dir}/bad | wc -l)
[ "$num_records" -eq 6 ] && ok || failed

echo "...returns an error if it cannot find any matching entry"
$PW_SHOW_GOOD 'non-existing' && failed || ok

echo "...searches on all fields"
pw=$($PW_SHOW_GOOD 'hidden-entry6')
[ "$pw" = "pw6" ] && ok || failed

echo "...searches only certain fields (part 1, the correct ones)"
pw=$($PW_SHOW_GOOD -s 'PIN' '66')
[ "$pw" = "pw6" ] && ok || failed

echo "...searches only certain fields (part 2, not others)"
$PW_SHOW_GOOD -s 'PIN' 'hidden-entry6' && failed || ok

echo "...searches only in labels (part 1, only in labels)"
pw=$($PW_SHOW_GOOD -l 'entry5')
[ "$pw" = "pw5" ] && ok || failed

echo "...searches only in labels (part 2, not in other fields)"
$PW_SHOW_GOOD -l 'hidden-entry6' && failed || ok

echo "...shows only the requested field"
pin=$($PW_SHOW_GOOD -f 'PIN' 'hidden-entry6')
[ "$pin" = "66" ] && ok || failed
